language: rust
sudo: required

rust:
  - stable

# spsps needs gcc 4.8 or greater
# Proper building with -fPIC needs CMake 3
before_install:
  # To deal with noisy scripts. If everything succeeds, be silent. If there is a failure, print everything. With terminal colors
  - function succeed_or_print() { COMMAND=""; while (( "$#" )); do COMMAND="$COMMAND $1"; shift; done;  script -e --command="$COMMAND" typescript 2>&1 > /dev/null || cat typescript; rm typescript; }
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:andykimpe/cmake3
  - sudo apt-get update -qq

install:
  - succeed_or_print sudo apt-get install -qq gcc-4.9
  - succeed_or_print sudo apt-get -yqq purge cmake
  - succeed_or_print sudo apt-get -yqq install cmake3
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - cd spsps
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - succeed_or_print VERBOSE=1 make
  - cd ../..
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls

